server:
  port: 5500
spring:
  profiles:
    active: profileActive
  application:
    name: vscing-java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ""
    username: ""
    password: ""
logging:
    level:
      root: WARN
      org:
        springframework:
          web: DEBUG
      com:
        example:
          myapp: INFO
# 启用 DEBUG 模式
debug: false

