# 服务端口
server:
  port: 5500
spring:
  profiles:
    active: '@profileActive@'
  application:
    name: vscing
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 或者 "path_pattern_parser"
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://8.152.192.61:5306/hiyafliy?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true'
    username: hiyafliy
    password: hiyafliy@888
logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    com.vscing.admin: INFO
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
mybatis:
  configuration:
#    log-impl: ${MYBATIS_LOG_IMPL:org.apache.ibatis.logging.stdout.StdOutImpl}
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath*:mapper/*.xml
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  expiration: 604800 #JWT的超期限时间(60*60*24*1)
  tokenHead: 'Bearer '  #JWT负载中拿到开头
secure:
  ignored:
    urls:
      - /v1/adminUser/login
      - /css/**
      - /js/**
      - /images/**
      - /swagger-ui/index.html
      - /v3/api-docs/**
# 启用 DEBUG 模式
debug: false

