# 服务端口
server:
  port: 5500
spring:
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: vscing
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 2MB
      # 设置总上传的文件大小
      max-request-size: 10MB
  mvc:
    # 设置静态资源路径 防止所有请求都去查静态资源
#    static-path-pattern: /static/**
#    format:
#      date-time: yyyy-MM-dd HH:mm:ss
    pathmatch:
      matching-strategy: ant_path_matcher # 或者 "path_pattern_parser"
logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    com.vscing.admin: INFO
    org.springdoc: DEBUG
    com.github.xiaoymin: DEBUG
#    com.vscing.model.mapper: DEBUG
  config: classpath:logback-spring.xml
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
#knife4j相关配置 可以不用改
knife4j:
  enable: true    #开启knife4j，无需添加@EnableKnife4j注解
  setting:
    language: zh_cn   #中文
    swagger-model-name: 实体类   #重命名SwaggerModel名称,默认
  #开启Swagger的Basic认证功能,默认是false
#  basic:
#    enable: true
#    # Basic认证用户名
#    username: root
#    # Basic认证密码
#    password: 1234567
mybatis:
  configuration:
#    log-impl: ${MYBATIS_LOG_IMPL:org.apache.ibatis.logging.stdout.StdOutImpl}
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath*:mapper/*.xml,classpath*:com/vscing/model/mapper/*.xml
#security:
#  users:
#    admin:
#      password: '{bcrypt}$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohZdumEBJV8CciViZknxbce5eh.' # 已经用BCrypt编码过的密码
#      roles: USER
# 启用 DEBUG 模式
debug: false
# 全局线程池相关配置
# 如使用JDK21请直接使用虚拟线程 不要开启此配置
thread-pool:
  # 是否开启线程池
  enabled: false
  # 队列最大长度
  queueCapacity: 128
  # 线程池维护线程所允许的空闲时间
  keepAliveSeconds: 300
ok:
  http:
    connect-timeout: 30
    read-timeout: 30
    write-timeout: 30
    # 连接池中整体的空闲连接的最大数量
    max-idle-connections: 100
    # 连接空闲时间最多为 60 秒
    keep-alive-duration: 60
