app:
  debug: false
spring:
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://localhost:5306/hiyafliy?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true'
    username: hiyafliy
    password: hiyafliy@88888
  data:
    redis:
      host: localhost
      port: 5300
      database: 0
      password: hiyafliy@888
      lettuce:
        pool:
          max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 8   # 连接池中的最大空闲连接
          min-idle: 0   # 连接池中的最小空闲连接
          max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        shutdown-timeout: 100ms # 关闭时等待时间
#        command-timeout: 5s # 命令超时时间
#        thread-local: false # 是否使用线程本地的连接
secure:
  ignored:
    enabled: true  # 安全校验开关，默认开启
    urls:
      - /v1/admin/login
      - /v1/task/address
      - /v1/task/cinema
      - /v1/task/movie
      - /v1/task/show
      - /css/**
      - /js/**
      - /images/**
