# 服务端口
server:
  port: 5500
spring:
  profiles:
    active: '@profileActive@'
  application:
    name: demo
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://localhost:3306/vdb?useUnicode=true&characterEncoding=utf8mb4&useSSL=false&serverTimezone=UTC'
    username: root
    password: 123456
logging:
  level:
    root: WARN
    org:
      springframework:
        web: DEBUG
    com:
      example:
        myapp: INFO
mybatis:
  configuration:
#    log-impl: ${MYBATIS_LOG_IMPL:org.apache.ibatis.logging.stdout.StdOutImpl}
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath*:mapper/*.xml
# 启用 DEBUG 模式
debug: false

