# 服务端口
server:
  port: 5500
spring:
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: vscing
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 或者 "path_pattern_parser"
logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    com.vscing.admin: INFO
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
mybatis:
  configuration:
#    log-impl: ${MYBATIS_LOG_IMPL:org.apache.ibatis.logging.stdout.StdOutImpl}
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath*:mapper/*.xml,classpath*:com/vscing/model/mapper/*.xml
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  expiration: 604800 #JWT的超期限时间(60*60*24*1)
  tokenHead: 'Bearer '  #JWT负载中拿到开头
#security:
#  users:
#    admin:
#      password: '{bcrypt}$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohZdumEBJV8CciViZknxbce5eh.' # 已经用BCrypt编码过的密码
#      roles: USER
secure:
  ignored:
    urls:
      - /v1/admin/login
      - /css/**
      - /js/**
      - /images/**
# 启用 DEBUG 模式
debug: false

