let data = {
	array:[
		{
			areaId: "",
			columnNo: "1",
			lie: "11",
			loveStatus: 0,
			pai: "1",
			rowNo: "1",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Ax5o6SMTHluqdAX0A0OUBfQDBAX0Ax5o6SMTHluqdAX0AzMDA1NA==",
			seatNo: "1排11座",
			status: "Y",
		},{
			areaId: "",
			columnNo: "2",
			lie: "10",
			loveStatus: 0,
			pai: "1",
			rowNo: "1",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Ax5o6SMTDluqdAX0A0OUBfQDBAX0Ax5o6SMTDluqdAX0AzMDA1NA==",
			seatNo: "1排10座",
			status: "N",
		},{
			areaId: "",
			columnNo: "3",
			lie: "9",
			loveStatus: 0,
			pai: "1",
			rowNo: "1",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Ax5o6SOeW6p0BfQDQ5QF9AMEBfQDHmjpI55bqnQF9AMzAwNTQ=",
			seatNo: "1排9座",
			status: "N",
		},{
			areaId: "",
			columnNo: "4",
			lie: "8",
			loveStatus: 0,
			pai: "1",
			rowNo: "1",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Ax5o6SOOW6p0BfQDQ5QF9AMEBfQDHmjpI45bqnQF9AMzAwNTQ=",
			seatNo: "1排8座",
			status: "N",
		},{
			areaId: "",
			columnNo: "5",
			lie: "7",
			loveStatus: 0,
			pai: "1",
			rowNo: "1",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Ax5o6SN+W6p0BfQDQ5QF9AMEBfQDHmjpI35bqnQF9AMzAwNTQ=",
			seatNo: "1排7座",
			status: "N",
		},{
			areaId: "",
			columnNo: "6",
			lie: "6",
			loveStatus: 0,
			pai: "1",
			rowNo: "1",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Ax5o6SNuW6p0BfQDQ5QF9AMEBfQDHmjpI25bqnQF9AMzAwNTQ=",
			seatNo: "1排6座",
			status: "N",
		},{
			areaId: "",
			columnNo: "7",
			lie: "5",
			loveStatus: 0,
			pai: "1",
			rowNo: "1",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Ax5o6SNeW6p0BfQDQ5QF9AMEBfQDHmjpI15bqnQF9AMzAwNTQ=",
			seatNo: "1排5座",
			status: "N",
		},{
			areaId: "",
			columnNo: "8",
			lie: "4",
			loveStatus: 0,
			pai: "1",
			rowNo: "1",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Ax5o6SNOW6p0BfQDQ5QF9AMEBfQDHmjpI05bqnQF9AMzAwNTQ=",
			seatNo: "1排4座",
			status: "N",
		},{
			areaId: "",
			columnNo: "9",
			lie: "3",
			loveStatus: 0,
			pai: "1",
			rowNo: "1",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Ax5o6SM+W6p0BfQDQ5QF9AMEBfQDHmjpIz5bqnQF9AMzAwNTQ=",
			seatNo: "1排3座",
			status: "N",
		},{
			areaId: "",
			columnNo: "10",
			lie: "2",
			loveStatus: 0,
			pai: "1",
			rowNo: "1",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Ax5o6SMuW6p0BfQDQ5QF9AMEBfQDHmjpIy5bqnQF9AMzAwNTQ=",
			seatNo: "1排2座",
			status: "N",
		},{
			areaId: "",
			columnNo: "11",
			lie: "1",
			loveStatus: 0,
			pai: "1",
			rowNo: "1",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Ax5o6SMeW6p0BfQDQ5QF9AMEBfQDHmjpIx5bqnQF9AMzAwNTQ=",
			seatNo: "1排1座",
			status: "N",
		},{
			areaId: "",
			columnNo: "1",
			lie: "11",
			loveStatus: 0,
			pai: "2",
			rowNo: "2",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Ay5o6SMTHluqdAX0A0OUBfQDBAX0Ay5o6SMTHluqdAX0AzMDA1NA==",
			seatNo: "2排11座",
			status: "N",
		},{
			areaId: "",
			columnNo: "2",
			lie: "10",
			loveStatus: 0,
			pai: "2",
			rowNo: "2",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Ay5o6SMTDluqdAX0A0OUBfQDBAX0Ay5o6SMTDluqdAX0AzMDA1NA==",
			seatNo: "2排10座",
			status: "N",
		},{
			areaId: "",
			columnNo: "3",
			lie: "9",
			loveStatus: 0,
			pai: "2",
			rowNo: "2",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Ay5o6SOeW6p0BfQDQ5QF9AMEBfQDLmjpI55bqnQF9AMzAwNTQ=",
			seatNo: "2排9座",
			status: "N",
		},{
			areaId: "",
			columnNo: "4",
			lie: "8",
			loveStatus: 0,
			pai: "2",
			rowNo: "2",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Ay5o6SOOW6p0BfQDQ5QF9AMEBfQDLmjpI45bqnQF9AMzAwNTQ=",
			seatNo: "2排8座",
			status: "N",
		},{
			areaId: "",
			columnNo: "5",
			lie: "7",
			loveStatus: 0,
			pai: "2",
			rowNo: "2",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Ay5o6SN+W6p0BfQDQ5QF9AMEBfQDLmjpI35bqnQF9AMzAwNTQ=",
			seatNo: "2排7座",
			status: "N",
		},{
			areaId: "",
			columnNo: "6",
			lie: "6",
			loveStatus: 0,
			pai: "2",
			rowNo: "2",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Ay5o6SNuW6p0BfQDQ5QF9AMEBfQDLmjpI25bqnQF9AMzAwNTQ=",
			seatNo: "2排6座",
			status: "N",
		},{
			areaId: "",
			columnNo: "7",
			lie: "5",
			loveStatus: 0,
			pai: "2",
			rowNo: "2",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Ay5o6SNeW6p0BfQDQ5QF9AMEBfQDLmjpI15bqnQF9AMzAwNTQ=",
			seatNo: "2排5座",
			status: "N",
		},{
			areaId: "",
			columnNo: "8",
			lie: "4",
			loveStatus: 0,
			pai: "2",
			rowNo: "2",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Ay5o6SNOW6p0BfQDQ5QF9AMEBfQDLmjpI05bqnQF9AMzAwNTQ=",
			seatNo: "2排4座",
			status: "N",
		},{
			areaId: "",
			columnNo: "9",
			lie: "3",
			loveStatus: 0,
			pai: "2",
			rowNo: "2",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Ay5o6SM+W6p0BfQDQ5QF9AMEBfQDLmjpIz5bqnQF9AMzAwNTQ=",
			seatNo: "2排3座",
			status: "N",
		},{
			areaId: "",
			columnNo: "10",
			lie: "2",
			loveStatus: 0,
			pai: "2",
			rowNo: "2",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Ay5o6SMuW6p0BfQDQ5QF9AMEBfQDLmjpIy5bqnQF9AMzAwNTQ=",
			seatNo: "2排2座",
			status: "N",
		},{
			areaId: "",
			columnNo: "11",
			lie: "1",
			loveStatus: 0,
			pai: "2",
			rowNo: "2",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Ay5o6SMeW6p0BfQDQ5QF9AMEBfQDLmjpIx5bqnQF9AMzAwNTQ=",
			seatNo: "2排1座",
			status: "N",
		},{
			areaId: "",
			columnNo: "2",
			lie: "10",
			loveStatus: 0,
			pai: "3",
			rowNo: "3",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Az5o6SMTDluqdAX0A0OUBfQDBAX0Az5o6SMTDluqdAX0AzMDA1NA==",
			seatNo: "3排10座",
			status: "N",
		},{
			areaId: "",
			columnNo: "3",
			lie: "9",
			loveStatus: 0,
			pai: "3",
			rowNo: "3",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Az5o6SOeW6p0BfQDQ5QF9AMEBfQDPmjpI55bqnQF9AMzAwNTQ=",
			seatNo: "3排9座",
			status: "N",
		},{
			areaId: "",
			columnNo: "4",
			lie: "8",
			loveStatus: 0,
			pai: "3",
			rowNo: "3",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Az5o6SOOW6p0BfQDQ5QF9AMEBfQDPmjpI45bqnQF9AMzAwNTQ=",
			seatNo: "3排8座",
			status: "N",
		},{
			areaId: "",
			columnNo: "5",
			lie: "7",
			loveStatus: 0,
			pai: "3",
			rowNo: "3",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Az5o6SN+W6p0BfQDQ5QF9AMEBfQDPmjpI35bqnQF9AMzAwNTQ=",
			seatNo: "3排7座",
			status: "N",
		},{
			areaId: "",
			columnNo: "6",
			lie: "6",
			loveStatus: 0,
			pai: "3",
			rowNo: "3",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Az5o6SNuW6p0BfQDQ5QF9AMEBfQDPmjpI25bqnQF9AMzAwNTQ=",
			seatNo: "3排6座",
			status: "N",
		},{
			areaId: "",
			columnNo: "7",
			lie: "5",
			loveStatus: 0,
			pai: "3",
			rowNo: "3",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Az5o6SNeW6p0BfQDQ5QF9AMEBfQDPmjpI15bqnQF9AMzAwNTQ=",
			seatNo: "3排5座",
			status: "N",
		},{
			areaId: "",
			columnNo: "8",
			lie: "4",
			loveStatus: 0,
			pai: "3",
			rowNo: "3",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Az5o6SNOW6p0BfQDQ5QF9AMEBfQDPmjpI05bqnQF9AMzAwNTQ=",
			seatNo: "3排4座",
			status: "N",
		},{
			areaId: "",
			columnNo: "9",
			lie: "3",
			loveStatus: 0,
			pai: "3",
			rowNo: "3",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Az5o6SM+W6p0BfQDQ5QF9AMEBfQDPmjpIz5bqnQF9AMzAwNTQ=",
			seatNo: "3排3座",
			status: "N",
		},{
			areaId: "",
			columnNo: "10",
			lie: "2",
			loveStatus: 0,
			pai: "3",
			rowNo: "3",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Az5o6SMuW6p0BfQDQ5QF9AMEBfQDPmjpIy5bqnQF9AMzAwNTQ=",
			seatNo: "3排2座",
			status: "N",
		},{
			areaId: "",
			columnNo: "11",
			lie: "1",
			loveStatus: 0,
			pai: "3",
			rowNo: "3",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0Az5o6SMeW6p0BfQDQ5QF9AMEBfQDPmjpIx5bqnQF9AMzAwNTQ=",
			seatNo: "3排1座",
			status: "N",
		},{
			areaId: "",
			columnNo: "4",
			lie: "6",
			loveStatus: 0,
			pai: "4",
			rowNo: "4",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A05o6SNuW6p0BfQDQ5QF9AMEBfQDTmjpI25bqnQF9AMzAwNTQ=",
			seatNo: "4排6座",
			status: "N",
		},{
			areaId: "",
			columnNo: "5",
			lie: "5",
			loveStatus: 0,
			pai: "4",
			rowNo: "4",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A05o6SNeW6p0BfQDQ5QF9AMEBfQDTmjpI15bqnQF9AMzAwNTQ=",
			seatNo: "4排5座",
			status: "N",
		},{
			areaId: "",
			columnNo: "6",
			lie: "4",
			loveStatus: 0,
			pai: "4",
			rowNo: "4",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A05o6SNOW6p0BfQDQ5QF9AMEBfQDTmjpI05bqnQF9AMzAwNTQ=",
			seatNo: "4排4座",
			status: "N",
		},{
			areaId: "",
			columnNo: "7",
			lie: "3",
			loveStatus: 0,
			pai: "4",
			rowNo: "4",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A05o6SM+W6p0BfQDQ5QF9AMEBfQDTmjpIz5bqnQF9AMzAwNTQ=",
			seatNo: "4排3座",
			status: "N",
		},{
			areaId: "",
			columnNo: "8",
			lie: "2",
			loveStatus: 0,
			pai: "4",
			rowNo: "4",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A05o6SMuW6p0BfQDQ5QF9AMEBfQDTmjpIy5bqnQF9AMzAwNTQ=",
			seatNo: "4排2座",
			status: "N",
		},{
			areaId: "",
			columnNo: "9",
			lie: "1",
			loveStatus: 0,
			pai: "4",
			rowNo: "4",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A05o6SMeW6p0BfQDQ5QF9AMEBfQDTmjpIx5bqnQF9AMzAwNTQ=",
			seatNo: "4排1座",
			status: "N",
		},{
			areaId: "",
			columnNo: "4",
			lie: "6",
			loveStatus: 0,
			pai: "5",
			rowNo: "5",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A15o6SNuW6p0BfQDQ5QF9AMEBfQDXmjpI25bqnQF9AMzAwNTQ=",
			seatNo: "5排6座",
			status: "N",
		},{
			areaId: "",
			columnNo: "5",
			lie: "5",
			loveStatus: 0,
			pai: "5",
			rowNo: "5",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A15o6SNeW6p0BfQDQ5QF9AMEBfQDXmjpI15bqnQF9AMzAwNTQ=",
			seatNo: "5排5座",
			status: "N",
		},{
			areaId: "",
			columnNo: "6",
			lie: "4",
			loveStatus: 0,
			pai: "5",
			rowNo: "5",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A15o6SNOW6p0BfQDQ5QF9AMEBfQDXmjpI05bqnQF9AMzAwNTQ=",
			seatNo: "5排4座",
			status: "N",
		},{
			areaId: "",
			columnNo: "7",
			lie: "3",
			loveStatus: 0,
			pai: "5",
			rowNo: "5",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A15o6SM+W6p0BfQDQ5QF9AMEBfQDXmjpIz5bqnQF9AMzAwNTQ=",
			seatNo: "5排3座",
			status: "N",
		},{
			areaId: "",
			columnNo: "8",
			lie: "2",
			loveStatus: 0,
			pai: "5",
			rowNo: "5",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A15o6SMuW6p0BfQDQ5QF9AMEBfQDXmjpIy5bqnQF9AMzAwNTQ=",
			seatNo: "5排2座",
			status: "N",
		},{
			areaId: "",
			columnNo: "9",
			lie: "1",
			loveStatus: 0,
			pai: "5",
			rowNo: "5",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A15o6SMeW6p0BfQDQ5QF9AMEBfQDXmjpIx5bqnQF9AMzAwNTQ=",
			seatNo: "5排1座",
			status: "N",
		},{
			areaId: "",
			columnNo: "4",
			lie: "6",
			loveStatus: 0,
			pai: "6",
			rowNo: "6",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A25o6SNuW6p0BfQDQ5QF9AMEBfQDbmjpI25bqnQF9AMzAwNTQ=",
			seatNo: "6排6座",
			status: "N",
		},{
			areaId: "",
			columnNo: "5",
			lie: "5",
			loveStatus: 0,
			pai: "6",
			rowNo: "6",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A25o6SNeW6p0BfQDQ5QF9AMEBfQDbmjpI15bqnQF9AMzAwNTQ=",
			seatNo: "6排5座",
			status: "N",
		},{
			areaId: "",
			columnNo: "6",
			lie: "4",
			loveStatus: 0,
			pai: "6",
			rowNo: "6",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A25o6SNOW6p0BfQDQ5QF9AMEBfQDbmjpI05bqnQF9AMzAwNTQ=",
			seatNo: "6排4座",
			status: "N",
		},{
			areaId: "",
			columnNo: "7",
			lie: "3",
			loveStatus: 0,
			pai: "6",
			rowNo: "6",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A25o6SM+W6p0BfQDQ5QF9AMEBfQDbmjpIz5bqnQF9AMzAwNTQ=",
			seatNo: "6排3座",
			status: "N",
		},{
			areaId: "",
			columnNo: "8",
			lie: "2",
			loveStatus: 0,
			pai: "6",
			rowNo: "6",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A25o6SMuW6p0BfQDQ5QF9AMEBfQDbmjpIy5bqnQF9AMzAwNTQ=",
			seatNo: "6排2座",
			status: "N",
		},{
			areaId: "",
			columnNo: "9",
			lie: "1",
			loveStatus: 0,
			pai: "6",
			rowNo: "6",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A25o6SMeW6p0BfQDQ5QF9AMEBfQDbmjpIx5bqnQF9AMzAwNTQ=",
			seatNo: "6排1座",
			status: "N",
		},{
			areaId: "",
			columnNo: "4",
			lie: "7",
			loveStatus: 0,
			pai: "7",
			rowNo: "7",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A35o6SN+W6p0BfQDQ5QF9AMEBfQDfmjpI35bqnQF9AMzAwNTQ=",
			seatNo: "7排7座",
			status: "N",
		},{
			areaId: "",
			columnNo: "5",
			lie: "6",
			loveStatus: 0,
			pai: "7",
			rowNo: "7",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A35o6SNuW6p0BfQDQ5QF9AMEBfQDfmjpI25bqnQF9AMzAwNTQ=",
			seatNo: "7排6座",
			status: "N",
		},{
			areaId: "",
			columnNo: "6",
			lie: "5",
			loveStatus: 0,
			pai: "7",
			rowNo: "7",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A35o6SNeW6p0BfQDQ5QF9AMEBfQDfmjpI15bqnQF9AMzAwNTQ=",
			seatNo: "7排5座",
			status: "N",
		},{
			areaId: "",
			columnNo: "7",
			lie: "4",
			loveStatus: 0,
			pai: "7",
			rowNo: "7",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A35o6SNOW6p0BfQDQ5QF9AMEBfQDfmjpI05bqnQF9AMzAwNTQ=",
			seatNo: "7排4座",
			status: "N",
		},{
			areaId: "",
			columnNo: "8",
			lie: "3",
			loveStatus: 0,
			pai: "7",
			rowNo: "7",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A35o6SM+W6p0BfQDQ5QF9AMEBfQDfmjpIz5bqnQF9AMzAwNTQ=",
			seatNo: "7排3座",
			status: "N",
		},{
			areaId: "",
			columnNo: "9",
			lie: "2",
			loveStatus: 0,
			pai: "7",
			rowNo: "7",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A35o6SMuW6p0BfQDQ5QF9AMEBfQDfmjpIy5bqnQF9AMzAwNTQ=",
			seatNo: "7排2座",
			status: "N",
		},{
			areaId: "",
			columnNo: "10",
			lie: "1",
			loveStatus: 0,
			pai: "7",
			rowNo: "7",
			seatId: "MjUyNDlAX0AxNDY2MjlAX0AxNjUyNTI4NDAwQF9AMTA5QF9ANDlAX0A35o6SMeW6p0BfQDQ5QF9AMEBfQDfmjpIx5bqnQF9AMzAwNTQ=",
			seatNo: "7排1座",
			status: "N",
		}
	]
}

export default data;
// module.exports = {
// 	data: data
// }